{'artist':'The Doors',
 'album':'The Very Best of the Doors',
 'genre':'Rock',
 'year':'2007',
 'titles':['Bird of Prey',
           'Love Her Madly',
           'Riders on the Storm',
           'Orange County Suite',
           'Runnin Blue',
           'Hello, I Love You',
           'The WASP (Texas Radio and the Big Beat)',
           'Stoned Immaculate',
           'Soul Kitchen',
           'Peace Frog',
           'L.A. Woman',
           'Waiting for the Sun',
           'Touch Me',
           'The Changeling',
           'Wishful Sinful',
           'Love Street',
           'Ghost Song',
           'Whiskey, Mystics and Men',
           'Roadhouse Blues']}
